# .github/workflows/test.yml

name: CI Test Suite

# Triggered on push or pull request to any branch
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v3

      # Set up Python version
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      # Install pytest
      - name: Install pytest
        run: |
          pip install pytest

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run unit tests
      - name: Run tests
        run: |
          pytest
